name: 'Merge command'

on: issue_comment

jobs:
  merge-command:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge command
      uses: Goobles/gh-actions-merge-command@v1
      with:
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
