name: AutoMerge

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - steps:
          - name: Get current time
            uses: gerred/actions/current-time@master
            id: current-time
          - name: Use current time
            env:
            TIME: "${{ steps.current-time.outputs.time }}"
            run: echo $TIME
      - name: automerge
        uses: pascalgn/automerge-action@v0.8.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_DELETE_BRANCH: true
