on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on master branch
      - master
jobs:
 slack:
    if: startsWith(github.ref, 'refs/tags/automerge')
    runs-on: ubuntu-latest
    steps:
    - name: Extract Branch Name
      run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "test :rocket: "
        SLACK_TITLE: Post Title
        SLACK_CHANNEL: test-pr-test
 
