name: SLACK
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    types: [closed]

jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
    - run: cat $GITHUB_EVENT_PATH
    - run: echo ${{ github.event_name }}
    - run: echo ${{ github.event.action }}
    - run: env
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  slack:
    if: contains(github.event.head_commit.message, 'Merged-with-githubaction')
    runs-on: ubuntu-latest
    steps:
    - name: Extract Branch Name
      run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "test :rocket: "
        SLACK_TITLE: Post Title
        SLACK_CHANNEL: test-pr-test
 
